[program:cicy-api]
command=/home/w3c_offical/projects/cicy-code/api/cicy-code-api
directory=/home/w3c_offical/projects/cicy-code/api
environment=TERM="xterm-256color",MYSQL_DSN="root:cicy-code@tcp(localhost:3306)/cicy_code",REDIS_ADDR="localhost:6379",PORT="8008",HOME="/home/w3c_offical"
user=w3c_offical
autostart=true
autorestart=true
stdout_logfile=/var/log/cicy-api.log
stderr_logfile=/var/log/cicy-api.log
