[program:code-server]
command=code-server --bind-addr 0.0.0.0:8002 --auth none /home/w3c_offical
directory=/home/w3c_offical
user=w3c_offical
environment=HOME="/home/w3c_offical",TERM="xterm-256color"
autostart=true
autorestart=true
stdout_logfile=/var/log/code-server.log
stderr_logfile=/var/log/code-server.log
