.PHONY: build run clean

build:
	export GOROOT=/usr/lib/go && go build -o cicy-dev-backend manager.go

run: build
	./cicy-dev-backend

clean:
	rm -f cicy-dev-backend

install: build
	cp cicy-dev-backend /usr/local/bin/
