FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y curl git && \
    curl -fsSL https://code-server.dev/install.sh | sh && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 8002
ENTRYPOINT ["code-server", "--bind-addr", "0.0.0.0:8002", "--auth", "none"]
CMD ["/home/cicy"]
