[program:cicy-api]
command=/bin/bash /home/w3c_offical/projects/cicy-code/api/run.sh
directory=/home/w3c_offical/projects/cicy-code/api
user=w3c_offical
autostart=true
autorestart=true
stdout_logfile=/var/log/cicy-api.log
stderr_logfile=/var/log/cicy-api.log
