ARG BASE_IMAGE=cicy-code-base:1.0.6
FROM ${BASE_IMAGE}

USER root

ARG APP_BINARY_HASH=unknown

LABEL cicy.app_binary_hash="${APP_BINARY_HASH}"

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
COPY --chown=cicy:cicy mgr/.tmux.conf /home/cicy/.tmux.conf
COPY --chown=cicy:cicy mgr/.cicy_tmux.conf /home/cicy/.cicy_tmux.conf
RUN chmod +x /usr/local/bin/docker-entrypoint.sh && \
    chown -R cicy:cicy /usr/local/lib/node_modules /usr/local/bin

WORKDIR /app
COPY --chown=cicy:cicy cicy-code-docker /app/cicy-code
RUN chown -R cicy:cicy /app && \
    touch /home/cicy/.bashrc && \
    grep -Fqx '[ -f "$HOME/.cicy_tmux.conf" ] && source "$HOME/.cicy_tmux.conf"' /home/cicy/.bashrc || \
      printf '%s\n' '[ -f "$HOME/.cicy_tmux.conf" ] && source "$HOME/.cicy_tmux.conf"' >> /home/cicy/.bashrc
USER cicy
ENV HOME=/home/cicy \
    TERM=xterm-256color \
    COLORTERM=truecolor \
    PATH="/home/cicy/.npm-global/bin:/home/cicy/.local/bin:/home/cicy/.opencode/bin:${PATH}"
EXPOSE 8008
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
