ARG BASE_IMAGE=cicy-code-base:1.0.2
FROM ${BASE_IMAGE}

ARG SETUP_AGENT_HASH=unknown
ARG APP_BINARY_HASH=unknown

LABEL cicy.setup_agent_hash="${SETUP_AGENT_HASH}" \
      cicy.app_binary_hash="${APP_BINARY_HASH}"

COPY setup-agent.sh /usr/local/bin/setup-agent.sh
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/setup-agent.sh /usr/local/bin/docker-entrypoint.sh

WORKDIR /app
COPY --chown=cicy:cicy cicy-code-docker /app/cicy-code
RUN chown -R cicy:cicy /app
USER cicy
EXPOSE 8008
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
